---
{{- if .Values.maxUnavailable }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "uname" . }}-pdb"
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace | quote }}
{{- end }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      app: "{{ template "uname" . }}"
{{- end }}
